# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='average_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='row',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='banner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='event',
            name='performers',
        ),
        migrations.AddField(
            model_name='event',
            name='performers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.Performer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='delivery_method',
            field=models.CharField(default='Electronic', max_length=255),
        ),
        migrations.AlterField(
            model_name='performer',
            name='thumbnail',
            field=models.CharField(default='', max_length=255),
        ),
    ]
