# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180327_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='thumbnail',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
